// Default body illustrations bundled with the package.
//
// IMPORTANT: 01_male_front_white.png currently ships as a lightweight PLACEHOLDER
// (generated by scripts/gen-placeholder.mjs). Replace it with the real
// 2048x3072 render before publishing. Masks are authored against that exact body
// version, so the image and the masks must come from the same source.
//
// The `new URL(..., import.meta.url)` form is understood by Vite, webpack 5,
// Rollup, esbuild/tsup and native ESM: each rewrites it to the emitted asset URL.
// This keeps the JS engine light instead of inlining the image as base64.

export const defaultBodyFront: string = new URL('./01_male_front_white.png', import.meta.url).href;

/** No back-view body image shipped yet. */
export const defaultBodyBack: string | null = null;
